### ISSUE TITLE
File extensions

### ISSUE THREAD

**Issue by areebbeigh** [martin-ueding/type-speed#1]
The file extensions for the python files are missing..

**Comment by martin-ueding** [comment]
When I built this, I just installed it into `/usr/bin` on a Linux machine. There the `.py` would be misplaced as it is uncommon for executables to have a file extension. Nowadays I use `setuptools` and then I would have the `.py` for the file and the `setup.py` would then create the entry point scripts that go into `/usr/bin`.

I could change that if you would like that. It might not make too much sense as this is a really small project and the build process would be more complicated than the project itself. But I see that even for small projects a proper project management can be nice.

So should I add a `setup.py` and `setuptools` to the mix? Or should I just rather add the `.py` and rename it with the `makefile` on installation?

**Comment by martin-ueding** [comment]
On your other projects I saw that you are a Windows based developer. Of course, there it does not make much sense to have a Python script without the `.py` file extension. So you would probably prefer the `setuptools` route as you do not have Make on Windows?

**Comment by areebbeigh** [comment]
setuptools would be better, yes.

**Comment by martin-ueding** [comment]
Okay, I will add a `setup.py` in about two weeks when I have some spare time.
